project_id = "zigemhmhbzegwbgvvmpc"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.ballotpedia-scraper]
    verify_jwt = false
