project_id = "zigemhmhbzegwbgvvmpc"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.ballotpedia-scraper]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.get-stripe-price]
    verify_jwt = false
  [functions.payments-webhook]
    verify_jwt = false
  [functions.cancel-subscription]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.notify-security-incident]
    verify_jwt = true
  [functions.handle-email-events]
    verify_jwt = false
