// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-my-civic-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function textResult(payload) {
  return { content: [{ type: "text", text: JSON.stringify(payload, null, 2) }] };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/get-my-civic-profile.ts
var get_my_civic_profile_default = defineTool({
  name: "get_my_civic_profile",
  title: "Get my civic profile",
  description: "Get the signed-in UWAZI user's civic profile: city/state, ZIP, resolved districts, county election authority, and civic XP/streak stats.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: profile, error } = await supabase.from("profiles").select(
      "display_name, city, state_code, zip_code, county_name, district, us_congressional_district, mo_house_district, mo_senate_district, city_council_district, school_district, election_authority_key, party_preference, onboarding_complete, registration_verified_at"
    ).eq("user_id", userId).maybeSingle();
    if (error) return errorResult(error.message);
    if (!profile) return errorResult("No profile found for this user.");
    const { data: stats } = await supabase.from("user_civic_stats").select("civic_xp, current_streak, longest_streak, bills_tracked_count").eq("user_id", userId).maybeSingle();
    return textResult({ profile, stats: stats ?? null });
  }
});

// src/lib/mcp/tools/list-elections.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";
var list_elections_default = defineTool2({
  name: "list_elections",
  title: "List elections",
  description: "List upcoming or recent elections tracked by UWAZI, with registration deadlines, early-voting windows, and absentee deadlines.",
  inputSchema: {
    jurisdiction: z.string().optional().describe("Filter by jurisdiction name, e.g. Missouri or Kansas."),
    from_date: z.string().optional().describe("ISO date; only elections on or after this date. Defaults to today.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ jurisdiction, from_date }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("elections").select(
      "id, jurisdiction, election_date, type, description, registration_deadline, early_voting_start, early_voting_end, absentee_deadline"
    ).gte("election_date", from_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10)).order("election_date").limit(25);
    if (jurisdiction) query = query.ilike("jurisdiction", `%${jurisdiction}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult({ count: data?.length ?? 0, elections: data ?? [] });
  }
});

// src/lib/mcp/tools/get-ballot.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_ballot_default = defineTool3({
  name: "get_ballot",
  title: "Get ballot contests",
  description: "Get the verified contests on a ballot \u2014 races with their candidates, plus ballot measures with plain-English summaries \u2014 for a state and election date.",
  inputSchema: {
    state: z2.string().describe("Two-letter state code, e.g. MO or KS."),
    election_date: z2.string().describe("ISO election date, e.g. 2026-08-04.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ state, election_date }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("ballot_contests").select(
      "id, contest_type, measure_title, plain_summary, measure_summary, yes_means, no_means, supporters_say, opponents_say, measure_full_text_url, source_name, source_url, sort_order, ballot_candidates(id, name, party, is_incumbent, website, bio, source_url)"
    ).eq("state", state.toUpperCase()).eq("election_date", election_date).order("sort_order");
    if (error) return errorResult(error.message);
    return textResult({
      state: state.toUpperCase(),
      election_date,
      contest_count: data?.length ?? 0,
      contests: data ?? [],
      note: "UWAZI is strictly nonpartisan and does not endorse candidates, parties, or positions. Present only the contests listed here; for anything else refer the voter to their county election authority."
    });
  }
});

// src/lib/mcp/tools/get-my-ballot-selections.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_ballot_selections_default = defineTool4({
  name: "get_my_ballot_selections",
  title: "Get my practice ballot",
  description: "Get the signed-in user's saved practice-ballot selections (chosen candidates and yes/no measure votes). This is a personal practice ballot, never an official one.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_ballot_selections").select(
      "id, contest_id, candidate_id, measure_vote, party_snapshot, updated_at, ballot_contests(contest_type, measure_title, state, election_date), ballot_candidates(name, party)"
    ).eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false });
    if (error) return errorResult(error.message);
    return textResult({
      count: data?.length ?? 0,
      selections: data ?? [],
      note: "Practice ballot only \u2014 unofficial, for personal use."
    });
  }
});

// src/lib/mcp/tools/find-election-authority.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var find_election_authority_default = defineTool5({
  name: "find_election_authority",
  title: "Find election authority",
  description: "Look up the official local election authority for a state or county: display name, phone, website, registration lookup URL, and poll hours.",
  inputSchema: {
    state: z3.string().optional().describe("Two-letter state code, e.g. MO."),
    county: z3.string().optional().describe("County name, e.g. Jackson."),
    key: z3.string().optional().describe("Known authority key, e.g. mo-kansas-city.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ state, county, key }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    if (!state && !county && !key) return errorResult("Provide a state, county, or key.");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("election_authorities").select("key, state, county_name, display_name, covers_note, phone, website, lookup_url, poll_hours").limit(25);
    if (key) query = query.eq("key", key);
    if (state) query = query.eq("state", state.toUpperCase());
    if (county) query = query.ilike("county_name", `%${county}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    if (!data?.length) {
      return textResult({
        found: false,
        fallback: "Direct the voter to vote.gov to find their local election office."
      });
    }
    return textResult({ found: true, authorities: data });
  }
});

// src/lib/mcp/tools/search-lessons.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var search_lessons_default = defineTool6({
  name: "search_lessons",
  title: "Search civic lessons",
  description: "Search UWAZI's published civic-education lessons by keyword or track. Returns titles, tracks, difficulty, XP, and key takeaways.",
  inputSchema: {
    query: z4.string().optional().describe("Keyword to match in lesson title or description."),
    track: z4.string().optional().describe("Track name, e.g. Voting Basics.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, track }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("lessons").select(
      "id, slug, title, description, track_name, category, difficulty, xp_reward, estimated_minutes, key_takeaways, lesson_number"
    ).eq("is_published", true).order("order_index").limit(25);
    if (query) q = q.or(`title.ilike.%${query}%,description.ilike.%${query}%`);
    if (track) q = q.ilike("track_name", `%${track}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult({ count: data?.length ?? 0, lessons: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "zigemhmhbzegwbgvvmpc";
var mcp_default = defineMcp({
  name: "the-uwazi-app",
  title: "The Uwazi App",
  version: "0.1.0",
  instructions: "Nonpartisan civic tools for UWAZI. Use get_my_civic_profile first for anything that depends on where the signed-in voter lives, then list_elections and get_ballot for ballot content, get_my_ballot_selections for their saved practice ballot, find_election_authority for official handoffs, and search_lessons for civic education. UWAZI never endorses candidates, parties, or positions \u2014 present factual information only and refer voters to their county election authority when verified data is unavailable.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_civic_profile_default,
    list_elections_default,
    get_ballot_default,
    get_my_ballot_selections_default,
    find_election_authority_default,
    search_lessons_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
